name: android-build
on :
  pull_request :
    branches : [ main ]
  push :
    branches: [ main ]
jobs:
  build:
    runs-on : ubuntu-latest
    steps:
      - name : Checkout
        uses : actions/checkout@v4.1.0

      - name : Setup Java SDK
        uses : actions/setup-java@v4.2.2
        with :
          java-version: '17'
          distribution: 'adopt'

      - name : Build with Gradle
        run : ./gradlew build

      - name: Build all artifacts
        id: buildAllApks
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: assembleRelease

      - name: Generate Release Notes
        run: |
          echo "Release Notes for build on $(date +"%d-%m-%Y %I:%M %p")" > release-notes.txt
          echo "-----------------------------------" >> release-notes.txt
          git log -5 --pretty=format:"%h - %s (%an)" >> release-notes.txt
        shell: bash

      - name: Upload Release Notes
        uses: actions/upload-artifact@v3.1.3
        with:
          name: release-notes.txt
          path: release-notes.txt