name: android-build
on :
    pull_request :
      branches : [ main ]
    push :
      branches: [ main ]
jobs:
  build:
    runs-on : ubuntu-latest
    steps:
      - name : Checkout
        uses : actions/checkout@v4.1.0

      - name : Setup Java SDK
        uses : actions/setup-java@v4.2.2
        with :
          java-version: '17'
          distributions: 'zulu'

      - name : Build with Gradle
        uses : ./gradlew build

      - name : Upload a Build Artifact
        uses : actions/upload-artifact@v3.1.3
        with :
          name : SonarQubeAutomation.apk
          path : app/build/outputs/apk/debug/app-debug.apk